language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - android-28

jdk:
  - openjdk8

before_install:
  - ./check-missing-assertions.sh

script:
  - ./gradlew clean check --no-daemon -Dkotlin.compiler.execution.strategy="in-process"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "SKhv6PsWxcaoO/c86Wk47447MXdI0aulO/wjrLGCVIgJwkKKkgtLY23RbAVjSk0ov0JZeXPqitF0x+w1e41s0fWc1LSVxF6Dq4bxCvjdr0K/vkoxsL/1SHnlafwqdm2QJiqnOcGaDKNKub8x8BcSvfLNaxG7jx5nHqL89zX/qUomwtZ0VmcHT3OlBoPu2VJPTdetSdI9Z8zAK44a+E6pKsgedZKDesKsQYk6YmCY9LMCcN4p2tuhYDLS7DyNvOLI+4OMFaE3KV7MJK+x7xXjvD9zkDV+BRFPs3fhV4VZzhO9pIpfeKcbL9JU9CKX8DR6XZfxjChyziihUTkU3TaZCKGgfAwURhgqOhP9oElqi3jPiMyik8eIcGDFeA9UURyrNjn08bc4Zxb1W5jkOGn21i4DijOsDIkZgbXL89JREktSreumm/Wrrp+pJyXU5U2PzvbcM3qV4a0FqkFKUJ75upL2W09ZOzi+bbi7xjKLSPF9171W69UazXUmHKKs62OvEsBO5sBA7+g0MICBg85FHqGXwQgHwjdP8ch8bybik5rmtWvxReQ9NWUUGdmCvEGFbqipzBJXyAWCBYp5/Lc+bwq4OeiahQaWckbqyaHwNMadYwxeXU/ol2In5pfY4wPZ+MiUcDuZ0zTCjZP5iXaqDapZ1AY6XnRZIZqv7CR24cI="
    - secure: "v7Be/25WqM1YxBQmcAMLAW4CaNkfkNOKBPH1J5bs1BOpoxjuzqrXEnpvDUMM7AKQ3R9IqAfd5HPESHBFHWN03vM2AXi4ldncfGOi+wepZRqp7OqCiM3cZrIzDdk3S5Itg9/7I+aFpo6f8sK6NWPE2xozTBxncYKYV4x6oVWrYkDxNxy6hS6/zIonypaKytnDLpcuN6k6wh6w2DIZA/yQYwLLFTJ96P9YLVBsAnbOr5K+7hycHRlKy0CNJCrz376i8AssbFlHK+3EpnjKsuFT6ama5QkOQ622ZQBrj9GkHo0LiYyNp9sk1emUoDRVVvmB3FUCmUACb/q67Ebg+u2q8vStKjHQekrGpo5de6X4IQPz/GFapl/0AovQYHdVPHEsosRIaQFE2ujBQpHXytm5ilUOXqolEFKrS8GTYwPkCNwKM+Y+cUU+dEOAlNcDD9BwuZBy7dgi7B52viEFV3de7hYoI+btdjLy9GWTArFLJUohTv7gYW5xzOEVQ6Xod81AbFW1rGhfp4zicyVQYc1nNUX0yBwNSfkDDpEowUX2BkG+rtYxXV4MsBQDqq6NqnNRNxVwpqm/cI/zAwkiPG5dYNd6LtGAqoMke4/XPU7RYDj1a8u+qzt3c/cW8LKnqld8EW3Rg2KUTJGaiFpHAj/9FxJWlmrkQuEtZwSuMGYUu5o="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
